# Generated by Django 3.0.7 on 2020-10-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='firstname',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='lastname',
            field=models.CharField(default='sample', max_length=30),
            preserve_default=False,
        ),
    ]
